[build]
target = "index.html"       # The index HTML file to drive the bundling process.
html_output = "index.html"  # The name of the output HTML file.
release = false             # Build in release mode.
dist = "dist"
public_url = "/"
filehash = true
inject_scripts = true
offline = false
frozen = false
locked = false
minify = "never"
